airbrake/airbrake

lib/airbrake/tasks/airbrake.cap
I was setting up a new deployment in cap3 after migrating from cap2.  I did not have an :app role defined for my stages, only :web and :db.  This caused the airbrake notification not to happen.  I recommend that this be changed to :all role to keep that from happening.
Looking at the file history, this is actually how it used to be defined.  Was this changed to :app for any reason?
=> Assumption of existence of :app role may not be valid

lib/airbrake/rails/controller_methods.rb
According to the issue: https://github.com/rails/rails/issues/16926
When rails version > 4.1.6, request.fullpath no longer has leading /, which will break Airbrake::Rails::ControllerMethods#airbrake_request_url, so make the code support those two cases.
=> fix bug: rails request.fullpath behavior change in 4.1.6 -- no longer has leading /

lib/airbrake.rb
I wanted to pass additional context about errors and tried to search documentation.
Looking at Airbrake#notify method seems like it doesn't accept parameters:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake.rb#L130
Comments above don't mention parameters hash.
But digging deeper I found:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/notice.rb#L111
Indeed it works. This pull request is attempt to improve `notify` method documentation.
=> Improves documentation for notify method

lib/airbrake/rails/controller_methods.rb
In some Rails 4 configurations, `ActiveRecord` is defined, but `ActiveRecord::Base` is not.
=> Support Rails 4 without ActiveRecord

lib/airbrake/rails.rb
Since Rack::Lock may not be available for app with websocket-rails
=> Insert UserInformer middleware before Rack::Runtime 

lib/airbrake/configuration.rb, lib/airbrake/notice.rb, lib/airbrake/utils/params_cleaner.rb, test/params_cleaner_test.rb
I found that filtering parameters from being sent to Airbrake using the :params_filters attribute is something that I constantly need to update and think about. (In my company we need to make sure no personal customer information is shared with 3rd party services)
Since there is only a small number of parameters I actually care about when examining an Airbrake notification, I think that the ability to whitelist the parameters I am interested in, is a simpler, safer approach.
By setting the :params_whitelist_filters list, all other parameters will be filtered (and their content replaced).
If a parameter is both whitelisted and "blacklisted" it will be filtered.
=> Add ability to define whitelist filters for parameters

lib/airbrake/sender.rb, test/sender_test.rb
This PR would fix #364 
In `Airbrake::Sender`, using the `URI.path` method [here](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/sender.rb#L54) the resulting URL is not compliant the format `/api/v3/projects/:project_id/notices?key=:api_key`.
IMHO, using [`request_url`](http://ruby-doc.org/stdlib-2.2.2/libdoc/uri/rdoc/URI/HTTP.html#method-i-request_uri) should fix this problem.
- Bug Report
4.3.0
ruby 1.9.3/2.2.1
```ruby
Airbrake.configure do |config|
config.api_key = "aaaaaaaa"
config.project_id = "000000"
config.host = "collect.airbrake.io"
end
```
From a IRB/PRY session:
```ruby
require 'airbrake' ; 
Airbrake.configure do |c| 
c.api_key = "000" ;  
c.environment_name = 'test' ;  
c.development_environments = []
end
Airbrake.notify(RuntimeError.new("[IGNORE_ME] ..." )) …
```
=> Fix missing api_key when using V3 endpoint URL

generators/airbrake/airbrake_generator.rb, generators/airbrake/templates/initializer.rb
Experienced issue #330 on Rails 4.2.3/Airbrake 4.3.0:
```
(erb):1:in `template': uninitialized constant Thor::Rails::VERSION (NameError)
from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
from /Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
from /Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
from /Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
from /Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
from /Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in …
```
=> Use ::Rails namespace for Rails::VERSION

lib/airbrake/notice.rb
Hallo. I have rails app (2.3.10), errbit (latest version for today).
In the case if I want generate airbrake notification with Airbrake.notify(e) it sends to errbit wrong xml, without data about error. This patch fix the problem.
=> Fix dumping notice object to xml for rails 2.3.10 and builder 2.1.2

lib/airbrake/rails/controller_methods.rb
For Rails 5 api-only apps, `ActionController::Parameters` has no `to_hash` method.
=> Fix airbrake/airbrake#410

lib/airbrake/capistrano.rb, lib/airbrake/shared_tasks.rb, lib/airbrake/tasks/airbrake.cap, lib/airbrake_tasks.rb, test/airbrake_tasks_test.rb
Removed "API_KEY" param being set in Capistrano tasks and airbrake:deploy task
due to possible conflict with ENV and since it's not needed there and is not
mentioned in Docs regarding deployment.
**Bug / Conflict with ENV variable description:**
If you have ENV variable called API_KEY either locally during deployment or
in your application used somewhere else, Airbrake.configuration.api_key will
be ignored and ENV variable called API_KEY used instead.
=> Remove "API_KEY" set from ENV Variable in Capistrano and airbrake:deploy

lib/airbrake/rails/controller_methods.rb, test/controller_methods_test.rb
=> [#419] don't fail on request param containing |

lib/airbrake/rails/controller_methods.rb, test/controller_methods_test.rb
=> Revert "[#419] don't fail on request param containing |"

lib/airbrake/utils/params_cleaner.rb, test/params_cleaner_test.rb
Fixes #396 (Airbrake attempting to close an already closed IO object)
This PR replaces #397.
=> params_cleaner: do not attempt to "collect" closed IO objects

test/controller_methods_test.rb
This test was previously checking the wrong thing. It was calling a
private method to load the user (`#airbrake_current_user`), then checking
that `#id` is never called on that user. However,
`#airbrake_current_user` never calls `#id` even when a valid user is
loaded. Therefore this test could never fail.
I've "corrected" it by making it call `#airbrake_request_data` instead,
which does attempt to call `#id` (this is also the method under test for
every other test in this context).
=> Corrected ControllerMethods test that could never fail

test/integration.rb
This is an attempt to fix #427. I'm not sure why we need to require it
explicitly, so let's try removing it.
=> test/integration: don't require abstract_controller

lib/airbrake/rails/controller_methods.rb, test/controller_methods_test.rb
Do no prepend / if already in `fullpath`
These commands are now successful:
```
bundle exec rake test:unit
bundle exec rake integration_test
```
=> [#419] Fix build 314

lib/airbrake/utils/params_cleaner.rb, test/params_cleaner_test.rb
Issue Type: Bug Report
Airbrake Gem Version: current (4.3.2)
Ruby Version: 2.3.2
Framework Name/Version: Rails 4.2.4
Airbrake Configuration: basic (only api-key in initializer)
Having cookies set with key, that should be filtered.
It should filter the cookie value. But in any case airbrake should not break (so it notifies at least about ANY error).
Airbrake breaks on params-filtering and nobody notices.
When cleaning cgi-data in `utils/params_cleaner.rb`, there might be cookies set on the key `action_dispatch.cookies` (Rails 4.2.4), which contain a filter-key. 
E.g.: 
```
@blacklist_filters = %(secret)
cgi_data = {
'action_dispatch.cookies' => [
['_session', 'htRkVDRGI1NEpNcElVNGZSdHRUR0hpdUxlWWJnZjRqUjFVaUVwNU1nSW9'],
['secret', 'usually this value would be filtered'],
]
}
```
This …
=> [Fix] filtering multidim-arrays from cgi-data's 'action_dispatch.cookies'

README.md
This is to minimise confusion for people who are looking for the old
code and its README.
=> Provide information about where to find the old code

lib/airbrake/capistrano/tasks.rb
Currently when we do a deployment all servers are triggering the deployment notification to Airbrake. This really only needs to happen once.
=> Only notify Airbrake of deployment from primary server

README.md, docs/Migration_guide_from_v4_to_v5.md
I'm not sure why I considered the hook is not needed. Even if it
worked without the hook for me, turns out defining it is a much
more robust solution.
Thanks to @nick-desteffen for [pointing this out][1]
[1]: https://github.com/airbrake/airbrake/pull/443#issuecomment-166363714
=> README,Migration_guide: fix Capistrano 3 instructions

docs/Migration_guide_from_v4_to_v5.md
Fixes #456 (Airbrake 5 -- "ActiveRecord::RecordNotFound" not ignored
by default)
=> migration_guide: mention the list of default ignored classes

Gemfile, gemfiles/rack.gemfile, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.0.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_edge.gemfile, gemfiles/sinatra.gemfile
I simply forgot to delete this when we released v5.
=> Update appraisals to use released airbrake-ruby

docs/Migration_guide_from_v4_to_v5.md
Between Airbrake v4 and v5 the default environments that are ignored has changed from `[:development, :test, :cucumber]` to `[]`. This means that any apps which did not explicitly define `ignore_environments` before and upgrade to v5 will suddenly start sending errors to airbrake in development and test.
=> Explained how to preserve the old value for development environments

lib/airbrake/configuration.rb
We're using the `airbrake` v4 gem with [Errbit](https://github.com/errbit/errbit) and ran into an issue where we're not able to verify our peer SSL certificate, which was issued from an internal CA.
I tried setting `use_system_ssl_cert_chain = true`, but was thwarted by the `File.exist?(OpenSSL::X509::DEFAULT_CERT_FILE)` check since our systems do not have a CA cert bundle where the `openssl` gem expects it. Leaving `http.ca_file` set to `nil` works fine, however, since `openssl` *does* have a correctly configured CA cert *directory*.
This PR makes it so that `use_system_ssl_cert_chain` is respected regardless of whether `OpenSSL::X509::DEFAULT_CERT_FILE` exists. If it does not exist, then the `openssl` library is allowed to use its normal behavior to find its SSL trust roots. Looking at …
=> Allow use_system_ssl_cert_chain to work with missing DEFAULT_CERT_FILE

CHANGELOG.md, lib/airbrake/rack/notice_builder.rb, lib/airbrake/rack/user.rb, spec/integration/rails/rails_spec.rb, spec/unit/rack/user_spec.rb
This change indirectly adds support for [OmniAuth][1] users. The way
OmniAuth integrates with Rails is described [here][2]. Note: this only
works for Rails apps, which I believe should be sufficient for now.
[1]: https://github.com/intridea/omniauth
[2]: https://github.com/testbrian/omniauth-github/blob/patch-2/README.md
=> rack: report current_user if it's available

CHANGELOG.md, lib/airbrake.rb
Fixes #449 (Airbrake 5 Breaks Debugging)
The problem occurs *only* in RubyMine. For some reason when running
tests with help of it (via the GUI) the `Rake` constant is defined,
but none of the Rake library is loaded. I tried to debug this for a
while, but couldn't find any clues.
The fix is to rely on other constant being present - `Rake::Task`.
=> airbrake: load Rake integration only if Rake::Task is defined

CHANGELOG.md, lib/airbrake.rb, lib/airbrake/capistrano/tasks.rb
Fixes #468 (Capistrano 2.x deployment notification broken)
The command we're running here should be run on the remote machine
(only once). The previous code was running it locally.
=> capistrano: fix the Capistrano 2 integration

lib/generators/airbrake_initializer.rb.erb
Apparently it's confusing for many people that 'ignore_environments'
doesn't work in certain conditions.
=> generators/airbrake_initializer: clarify 'ignore_environments'

CHANGELOG.md, lib/airbrake.rb, lib/airbrake/rack/notice_builder.rb
The new airbrake-ruby sends that information by default.
=> rack: rely on airbrake-ruby's hostname information

CHANGELOG.md, lib/airbrake/rack/user.rb, spec/unit/rack/user_spec.rb
Would otherwise cause an issue if the controller responds to current user but
the value was e.g. nil
Replaces #498 because the original author hasn't responded yet and I feel like it's a quite important addition.
=> rack: check if user is truthy before trying to build from it

lib/airbrake/rack/notice_builder.rb, spec/integration/shared_examples/rack_examples.rb
This is a follow-up to #499.
With the old approach the API can and probably will throw away our
data. Given that we're retrieving values about HTTP request from
the Rack env, let's attach it to the environment tab instead.
=> rack: move the Rack env payload to 'environment'

lib/airbrake/capistrano/tasks.rb
Restores the airbrake_env Capistrano option from Airbrake 4, as discussed in #506.
=> airbrake_env deployment notification option; fixes #506

docs/Migration_guide_from_v4_to_v5.md, lib/airbrake/rack/notice_builder.rb, spec/unit/rack/notice_builder_spec.rb
Information about ENV should be merged into the notice[:environment] to not replace already stored data. And `Airbrake::Rack::NoticeBuilder` should not replace lost information during building, too.
Please, take a look on this issue for additional details: https://git.io/vg1W0.
=> Existing information in the notice's environment should be merged, not replaced

CHANGELOG.md, lib/airbrake/rake/task_ext.rb
This allows us to send a notice before the Rake process quits.
Originally reported on [StackOverflow][1].
[1]: http://stackoverflow.com/q/35462531/511205
=> rake: make the integration synchronous

lib/airbrake.rb, lib/airbrake/rack/notice_builder.rb, spec/airbrake_spec.rb, spec/unit/rack/notice_builder_spec.rb
Allows users to add their own builders for notice. So, for example, if it's needed to add a `REMOTE_IP` in the notice's params it can be easily done in standard initializer for airbrake like this:
```ruby
Airbrake.add_rack_builder |notice, request|
notice[:params][:remoteIp] = request.env['REMOTE_IP']
end
```
=> Introduced user defined builders in Airbrake::Rack::NoticeBuilder (#509)

lib/airbrake/rack/middleware.rb, spec/unit/rack/middleware_spec.rb
In v4, Airbrake::Rack would check for framework-saved exceptions in the
Rack env under rack.exception or sinatra.error:
https://github.com/airbrake/airbrake/blob/34fcbe8e6aae20aad0e4f5174df16945dd6f1356/lib/airbrake/rack.rb#L60
Now v5's Airbrake::Rack::Middleware looks under
action_dispatch.exception or sinatra.error. I'm not sure whether Rails
or Sinatra ever set env['rack.exception'] on their own. That key does
not appear to be part of the Rack standard, and I can't find any trace
of the string 'rack.exception' in the Rails codebase, or even in a `git
log -G 'rack\.exception'`.
Presumably Rails (or maybe a middleware it depends on?) set that key at
some point, since Airbrake v4 checked for it. I also presume v5
continues to work fine with Rails and Sinatra. However, the
rack.exception …
=> Fix Airbrake::Rack::Middleware regression

CHANGELOG.md, lib/airbrake/rake/tasks.rb
Fixes #521 (Test rake task doesn't work for ignored environments)
=> rake: suggest how to airbrake:test when current env is ignored

CHANGELOG.md, README.md, airbrake.gemspec, lib/airbrake/version.rb
MINOR version bump because we started depending on airbrake-ruby-1.2.0.
=> Release v5.2.0

lib/generators/airbrake_initializer.rb.erb
This should've been in airbrake-5.2.0, but I forgot to update it :(
=> airbrake_initializer: update blacklist_keys to the new API

Appraisals
Newest `mime-types` gem dropped support for 1.9.3, so our build has
started failing. Locking down the gem version helps to fix it.
=> Appraisals: fix build for Ruby 1.9.3

CHANGELOG.md, lib/airbrake/rails/active_job.rb
Fixes #532 (Same exceptions occurred from ActiveJob have different
action values)
=> rails/active_job: amend `component` and `action` to fix grouping

CHANGELOG.md, lib/airbrake/rake/tasks.rb
If a project was configured with bad project ID or project key, the API
would return an error response. The Rake task, however, would print the
success text.
Instead, handle API errors and print a more relevant message. Example:
```
% bundle exec rake airbrake:test
Error occurred: Project not found or access denied.
Make sure that your Project ID and Project Key are correct:
https://github.com/airbrake/airbrake-ruby#project_id--project_key
```
=> rake: handle response errors

docs/Migration_guide_from_v4_to_v5.md
A customer was confused that we didn't mention this in the guide.
=> Migration_Guide: mention deprecation of 'filter_parameters'

lib/airbrake/rake/tasks.rb
At the moment errors cannot be resolved automatically on deploy because
Heroku doesn't send the environment information. To work around this we
attach environment to the URL
=> rake: attach env information to the Heroku deploy hook

CHANGELOG.md, lib/airbrake/rails/active_job.rb
Fixes #540 (Configuration for ActiveJob + Rescue).
This goes along with our Resque integration, which became synchronous.
=> rails/active_job: be synchronous is the adapter is resque

.rubocop.yml, Gemfile, lib/airbrake/rack/middleware.rb, lib/airbrake/rack/notice_builder.rb, lib/airbrake/rails/action_controller.rb, lib/airbrake/rails/active_job.rb, lib/airbrake/rake/task_ext.rb, spec/integration/rails/rails_spec.rb, spec/unit/rack/middleware_spec.rb, spec/unit/rack/notice_builder_spec.rb, spec/unit/rake/tasks_spec.rb
This change along with https://github.com/airbrake/airbrake-ruby/pull/75
fix https://github.com/airbrake/airbrake/issues/546.
Due to the breaking change in airbrake-ruby we need to update some of
our integrations that use `Airbrake.build_notice`.
/cc @khustochka (could you please verify if `airbrake-ruby` master with this PR work for you? I've done some manual testing and it is works good for me).
=> Adjust integrations to return early when 'build_notice' returns 'nil'

CHANGELOG.md, README.md, lib/airbrake/version.rb
Why v5.3.0 and not v5.2.4? Well, it's because airbrake-ruby's MINOR
version was bumped. SemVer doesn't define what to do in this situation.
This gem's API stays the same. However the logic here is that users are
directly affected by this change because airbrake-ruby doesn't raise
an important exception that it used to raise.
Depends on https://github.com/airbrake/airbrake/pull/548 & https://github.com/airbrake/airbrake/pull/549.
=> Release v5.3.0

lib/airbrake/utils/params_cleaner.rb, test/params_cleaner_test.rb
Issue Type: _Bug Report_
Airbrake Gem Version: **4.3.6**
Fix `#filter` method in `ParamsCleaner` class to be able to process nested arrays with any nesting level.
This error occurs in our sidekiq worker with unknown exact steps, but it can be easily reproduced in tests (which is done in this pull request).
According to [this page](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md), v4 is still supported and, I hope, is open for bug fixes, as we would like to avoid migration to v5 for our current production apps.
Thanks.
=> Fix params cleaner for deep nested arrays

lib/airbrake/rails/controller_methods.rb, test/controller_methods_test.rb
`ActiveRecord::Base.connection_pool.release_connection` handles
only one of connection_pools which belongs to `ActiveRecord::Base`.
When developers use `establish_connection` and `User` model uses
an established connection, we should use `clear_active_connections!`
to release all connection_pools.
=> Use `clear_active_connections!` instead of `release_connection`

spec/integration/sinatra/sinatra_spec.rb, spec/spec_helper.rb, spec/unit/sidekiq/error_handler_spec.rb
The bug was introduced by:
https://github.com/mperham/sidekiq/issues/3042
It resulted in loading Sinatra when we run tests against Rack (we
need Sidekiq for unit tests, so we load it).
Example build that fails:
https://circleci.com/gh/airbrake/airbrake/781
=> spec_helper: fix build by requiring sinatra in its test file

lib/airbrake/rails/railtie.rb, spec/integration/rails/rails_spec.rb
An alternative fix to https://github.com/airbrake/airbrake/pull/562.
We have to have this extra safety measure to ensure we don't leak DB
connections. More information:
https://blog.codefront.net/2009/06/15/activerecord-rails-metal-too-many-connections/
=> rails: insert our middleware after ConnectionManagement

CHANGELOG.md, lib/airbrake/rake/tasks.rb, spec/unit/rake/tasks_spec.rb
Fixes #574 (rake airbrake:install_heroku_deploy_hook parsing env vars
inocrrectly)
=> rake: fix parsing variable in Heroku deploy hook

CHANGELOG.md, lib/airbrake/rails/railtie.rb
Fixes #579 (Middleware ConnectionManagement only for ActiveRecord)
=> rails/railtie: fix support of apps, which don't use ActiveRecord

lib/airbrake/rails/active_record.rb
To avoid stomping on user model constants in ActiveRecord, inline the value in the one place it's used, and remove it. Replaces #587, closes #586.
=> Inline array and remove constant in ActiveRecord

CHANGELOG.md, lib/airbrake/rails/active_job.rb, spec/integration/rails/rails_spec.rb
Description by @confiks from https://github.com/airbrake/airbrake/pull/583:
> In pull request https://github.com/airbrake/airbrake-ruby/pull/75, code was introduced in every integration to return early when `build_notice` returns nil because Airbrake is not configured.
> In at least the ActiveJob integration, the exception is not re-raised when returning early, and thus any ActiveJob queue adapter will happily mark the job successfully completed.
> This pull request contains a fix for the ActiveJob integration
=> Always re-raise exception in ActiveJob integration (replaces #583)

lib/airbrake/rails/active_job.rb, spec/apps/rails/dummy_app.rb, spec/integration/rails/rails_spec.rb
Hi, I got SystemStackError and found tiny improvement for this gem 💎 
Since AS's `Object#as_json` simply dump all instance variables, setting
params with `#as_json` can waste resource. Moreover, if the job has
circular reference, calling `#as_json` fails with `SystemStackError`.
We can get parameter information safely by using
`ActiveJob::Base#serialize` method and it will be enough for this
use case.
How about stopping dumping all instance variables? I didn't found any reason to do this.
=> No SystemStackError with any active jobs

README.md
Fixes #599 (I get a 404. The second link in the README works.)
=> README: fix link to migration guide

.rubocop.yml
Fixes failing build.
The cop was introduced by:
https://github.com/bbatsov/rubocop/commit/96f308b4f5601f4642fadc5c5e2826d90df0c0f5
=> rubocop: configure the new Metrics/BlockLength cop

spec/integration/rails/rails_spec.rb
As promised, errors in those callbacks started raising exceptions
instead of logging them.
=> integration/rails: fix failing specs on rails 5.1.0.alpha

README.md
Fixes #608 (ActiveJob using DelayedJob notifies Airbrake twice)
Fixes #597 (One exception is send several times to Airbrake)
=> README: clarify how to avoid duplicate ActiveJob errors

lib/airbrake/rack/user.rb, spec/unit/rack/user_spec.rb
Fixes #618 
If there is a current_user method that requires parameters, skip calling it (to avoid crashing the app while reporting an exception)
=> Ignore current_user with > 0 params

CHANGELOG.md, lib/airbrake/rack/notice_builder.rb, spec/unit/rack/notice_builder_spec.rb
Fixes #623 (Rack: send payload of XML requests on POST)
=> rack/notice_builder: attach request body to notices

CHANGELOG.md, lib/airbrake/rack/notice_builder.rb, spec/unit/rack/notice_builder_spec.rb
Fixes #626 (Log full HTTP post data)
We can't really read the whole body because it will significantly
increase our average notice size. But we're trying to find the right
balance here and read more.
=> rack/notice_builder: read up to 4096 bytes from Rack request's body

README.md
Fixes https://github.com/airbrake/airbrake-ruby/issues/137
(Support deep keys)
=> README: mention the lack of filter_parameters sub-keys support

CHANGELOG.md, lib/airbrake/rack/user.rb, spec/integration/rails/rails_spec.rb
Fixes #641 (notify_airbrake persists user login during 422 error)
Replaces #642 (Prevent users from signing in during notify_airbrake)
=> rack/user: return early if Warden is present and no user found

Appraisals, CHANGELOG.md, README.md, airbrake.gemspec, circle.yml, spec/integration/rails/rails_spec.rb
* Remove support for 1.9.2 (official support ended on 2014-07-31)
* Remove support for 1.9.3 (official support ended on 2015-02-23)
* Remove support for JRuby 1.7.X (quote from JRuby: "The primary goal of
1.7 point releases is to fill out any missing compatibility issues
with Ruby 1.9.3)
=> Remove support for Ruby 1.9.2 & 1.9.3

lib/airbrake/delayed_job/plugin.rb, lib/airbrake/resque/failure.rb, lib/airbrake/sidekiq/error_handler.rb
Setting `component/action` like that was deprecated in
https://github.com/airbrake/airbrake-ruby/pull/151
=> Refactor some integrations to stop using deprecated API

CHANGELOG.md, lib/airbrake/version.rb
This is a release candidate. Given that we have lots of new changes
including some of public API deprecations, we need to test this better.
=> Release v5.7.0.rc.1

lib/airbrake/rack/context_filter.rb
This is an interesting situation.
I am writing a Grape API application using only Rack, however, I am using ActionMailer to send some emails in Sidekiq. Something inside one of the Action* gems is defining the module `Rails`, but it's not fully loaded, as I am not using Rails. So when Airbrake gets to the point where it wants to use the context filter, it fails because `version` is not defined in the `Rails` module.
This code just checks to see if version is a defined attribute or method of the module `Rails`.
=> only use Rails.version if it is defined

airbrake.gemspec, lib/airbrake.rb, lib/airbrake/shoryuken/error_handler.rb, spec/unit/shoryuken/error_handler_spec.rb
This PR ports [Honeybadger support for Shoryuken](https://github.com/honeybadger-io/honeybadger-ruby/pull/190) over to Airbrake.
=> Add Shoryuken support 

lib/generators/airbrake_initializer.rb.erb
Fixes #671 (Do not log HTTP_AUTHORIZATION header by default)
=> generators/airbrake_initializer: ignore HTTP_AUTHORIZATION header

lib/airbrake/rack/middleware.rb, lib/airbrake/rails/action_controller.rb, spec/unit/rack/middleware_spec.rb
The API was introduced in:
https://github.com/airbrake/airbrake-ruby/pull/168/
=> Use airbrake v1.8.0 API for accessing notifiers

CHANGELOG.md, lib/airbrake/rails/action_controller.rb
Horrible oversight and Rubocop didn't save me here :(
Luckily, this is not in any of the stable releases.
=> rails/action_controller: fix NameError

lib/airbrake/rack/middleware.rb, spec/unit/rack/middleware_spec.rb
Fixes #691 (undefined method `add_filter' for
nil:NilClass (NoMethodError) - when Airbrake is not configured)
=> rack/middleware: do not raise if no notifiers exist

CHANGELOG.md, lib/airbrake.rb
Fixes #695 (Airbrake.notify method is not safe in the rake tasks.)
=> airbrake: close default Airbrake notifier on exit

CHANGELOG.md, airbrake.gemspec
Release https://github.com/airbrake/airbrake-ruby/pull/185
=> gemspec: update airbrake-ruby to '~> 2.0'

CHANGELOG.md, lib/airbrake/rack/http_params_filter.rb, spec/unit/rack/http_params_filter_spec.rb
Fixes #715 (HttpParamsFilter overrides custom params)
=> Fix Rack integration overriding 'notice[:params]'

README.md, lib/airbrake.rb, lib/airbrake/delayed_job.rb, lib/airbrake/rake.rb, lib/airbrake/resque.rb, lib/airbrake/shoryuken.rb, lib/airbrake/sidekiq.rb, spec/spec_helper.rb, spec/unit/sidekiq/error_handler_spec.rb
This way we hide unnecessary implementation details, so users can reference an integration by its name.
=> Simplify manual inclusion of integrations

CHANGELOG.md, lib/airbrake/rake/tasks.rb
Fixes #714 (do not load airbrake initializer when environment is already
loaded and require it)
=> rake/tasks: don't load initializer when Airbrake is available

README.md
We mention preferring `notify_airbrake` to `Airbrake.notify` without first saying what `Airbrake.notify` is. This adds a link to the relevant section in the airbrake-ruby repo.
=> Include link to Airbrake.notify section in airbrake-ruby

airbrake.gemspec
https://github.com/airbrake/airbrake-ruby/pull/207
=> gemspec: lock airbrake-ruby to ('~> 2.2', '>= 2.2.1')

lib/airbrake/rack/context_filter.rb, lib/airbrake/rack/http_headers_filter.rb, lib/airbrake/rack/http_params_filter.rb, lib/airbrake/rack/request_body_filter.rb, lib/airbrake/rack/session_filter.rb
This weight ensures that we load these filters after `airbrake-ruby`
filters, but not after user defined filters.
=> airbrake/rack: set weight for all filters

.travis.yml, circle.yml, gemfiles/rack.gemfile, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.0.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.0.gemfile, gemfiles/sinatra.gemfile
JRuby makes our builds last more than 13 minutes. Circle waits on every
container to finish their current task before proceeding to the next
one. JRuby is always slow to boot, so other containers are idling while
JRuby works. By moving JRuby builds to Travis we can test JRuby and MRI
in parallel.
=> Run JRuby tests on Travis

circle.yml
No need to `bundle install` because we already do it inside a container.
=> circle: simplify config

CHANGELOG.md, lib/airbrake/rake/tasks.rb
Fixes #745 (Capistrano Deployment Notification stopped working in v6.1.0 Update)
`Airbrake::NilNotifier` was introduced in airbrake-ruby v2.1.0. This
check wasn't updated accordingly.
=> rake: check for NilNotifier

airbrake.gemspec
Release notes:
https://github.com/airbrake/airbrake-ruby/blob/master/CHANGELOG.md#v225-may-23-2017
=> gemspec: bump airbrake-ruby minimum version to v2.2.5

lib/airbrake/rake/tasks.rb
Depends on: https://github.com/airbrake/airbrake-ruby/pull/226
We can leverage promises to display user friendly messages and return
proper exit codes.
=> rake/tasks: improve feedback of 'airbrake:deploy'

CHANGELOG.md, lib/airbrake/logger.rb
The `SimpleDelegator` is not required by older Rubies. I stumbled upon
this bug on Ruby 2.1.10 when generating Airbrake Rails config:
```
% rails g airbrake 1 2
...
Gem Load Error is: uninitialized constant Airbrake::SimpleDelegator
Backtrace for gem load error is:
/Users/kyrylo/.gem/ruby/2.1.10/gems/airbrake-6.1.1/lib/airbrake/logger.rb:14:in `<module:Airbrake>'
```
=> logger: require 'delegate'

lib/airbrake/rack/context_filter.rb, spec/unit/rack/context_filter_spec.rb
Checked with Airbrake today and learned that user addresses were not being included in notices. This is particularly confusing on Heroku, as only AWS addresses are reported.
This adds `userAddr` to notices and relies on Rack's well-tested `#ip` method. https://github.com/rack/rack/blob/c1437097dcdf92d53a692ca8135a3391791fbca3/lib/rack/request.rb#L256-L265
=> Append userAddr to context

lib/airbrake/rack/user.rb, spec/unit/rack/user_spec.rb
If attribute methods are overwritten to have parameters
e.g.
```
class User < ApplicationRecord
def name(formating)
end
end
```
Airbrake will fail with error `ArgumentError (wrong number of arguments (given 0, expected 1))`
and no error message will be sent to Airbrake
=> Don't call methods of @user if parameters are required

airbrake.gemspec, spec/unit/sidekiq_spec.rb
Sidekiq v5.0.4 has a Ruby version restriction now:
https://github.com/mperham/sidekiq/commit/7b66865a7c2b9bc6325697f63c2cbaea5a06019d
=> gemspec: test sidekiq only on Ruby >= 2.2.2

CHANGELOG.md, lib/airbrake/rake/tasks.rb
Fixes #762 (`rake airbrake:deploy` doesn't seem to work in a non-Rails
project)
=> rake: fix the deploy and test tasks for plain ruby projects

airbrake.gemspec
This fixes the following failure:
https://circleci.com/gh/airbrake/airbrake/1484
=> gemspec: lock public_suffix to v2

CHANGELOG.md, lib/airbrake/capistrano/capistrano2.rb
Fixes #777 (Capistrano v2 task no longer honors airbrake_env)
=> capistrano/capistrano2: port airbrake_env from airbrake v4

.rubocop.yml, spec/spec_helper.rb
* rubocop: don't enable already enabled [by default] cops
* rubocop: fix "wrong namespace" warnings
As seen in https://circleci.com/gh/airbrake/airbrake/1490#tests/containers/4
* rubocop: fix offences of the Naming/HeredocDelimiterNaming cop
=> Fix rubocop offences and warnings

.hound.yml
We use custom Rubocop rules and Hound can't see them. Inside the config we tell
Hound to respect our rules: https://houndci.com/configuration#ruby
=> Add hound.yml

lib/airbrake/rails.rb
Sometimes I get the error `NameError:  uninitialized constant Airbrake::Rails::ActiveRecord::ConnectionAdapters`
I believe this is happening because `lib/airbrake/rails/active_record.rb` has been required  and thus the constant `Airbrake::Rails::ActiveRecord` is being referenced instead of `::ActiveRecord`
My guess is that the order the `initalizer`'s are run is not necessarily the order in which they are defined in the file and `initializer('airbrake.active_record')` which requires `airbrake/rails/active_record.rb` is being run before `initializer('airbrake.middleware')`.
By referencing back to the root scope, '::', it fixes the error.
* Rails 4.2
* Airbrake 6.2.1
* Airbrake-ruby 2.3.2
=> fix reference to ActiveRecord

CHANGELOG.md, README.md, lib/airbrake/delayed_job.rb, lib/airbrake/rails/active_job.rb, lib/airbrake/resque.rb, lib/airbrake/sidekiq.rb, spec/integration/rails/rails_spec.rb
Fixes #608 (ActiveJob using DelayedJob notifies Airbrake twice)
Due to deduplication changes we also have to fix `action` for each integration
because the old code would report an adapter as `action`.
=> active_job: deduplicate notices

CHANGELOG.md, lib/airbrake/capistrano/tasks.rb, lib/airbrake/delayed_job/plugin.rb, lib/airbrake/logger/airbrake_logger.rb, lib/airbrake/rails/railtie.rb, lib/airbrake/rake/task_ext.rb, lib/airbrake/resque/failure.rb, lib/airbrake/shoryuken/error_handler.rb, lib/airbrake/sidekiq/error_handler.rb
These were deprecated 5 months ago, so it's high time to get rid of them.
=> Delete deprecated require paths for some integrations

CHANGELOG.md, lib/airbrake/capistrano/capistrano2.rb
Fixes https://github.com/airbrake/airbrake/issues/795.
Apparently the username method is not accessible from that scope. The only
reason it was a method is to reduce AbcSize complexity, but now it seems to be
safer to ignore that metrics.
=> capistrano/capistrano2: fix NameError

lib/airbrake/sidekiq.rb
If ActiveJob is not used, you can for example have args that are `[1, 2, 3]`, which will not be caught by `return klass unless context[:job] && context[:job]['args'].first`.
This causes next line to fail with `no implicit conversion of String into Integer`.
Suggested fix: Only try to lookup 'job_class' if context[:job]['args'].first is a hash.
=> Fix Sidekiq action(context)

CHANGELOG.md, lib/airbrake/rack/middleware.rb
Fixes #802 (Airbrake reporting ALL urls as secure with a port)
`ActionDipstach::Request` and `Rack::Request` are not the same. We should use
the former when it's available because it handles SSL port better.
=> rack/middleware: use ActionDispatch::Request when available

docs/Migration_guide_from_v4_to_v5.md
I was confused what happened to the `user_attributes` after upgrading from Airbrake v4 to v7 and the migration guide simply mentioned that the feature was removed, but didn't mention how user attributes were obtained in the new version.
I've updated the migration guide to document the new behavior as discussed with @kyrylo in #604.
=> Document what happened to user_attributes in v5

spec/integration/rails/rake_spec.rb, spec/integration/shared_examples/rack_examples.rb, spec/integration/sinatra/sinatra_spec.rb, spec/unit/logger_spec.rb, spec/unit/rack/middleware_spec.rb, spec/unit/rack/user_spec.rb, spec/unit/rake/tasks_spec.rb, spec/unit/shoryuken_spec.rb, spec/unit/sidekiq_spec.rb
In the most recent airbrake-ruby project key is passed through the Authorization
header, not a query parameter. [1]
[1]: https://github.com/airbrake/airbrake-ruby/commit/5d258a28993ca2b2649e02abd93dfa944f207063
=> spec: don't pass key for notice stubs

spec/unit/rake/tasks_spec.rb
Deploys still require the `key` query param.
=> spec/unit/rake/tasks: use key for deploys requests

Appraisals, airbrake.gemspec, circle.yml, gemfiles/rack.gemfile, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.0.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile, gemfiles/rails_edge.gemfile, gemfiles/sinatra.gemfile
Rack test v0.8.0+ added a required_ruby_version of >= 2.2.2 but we still need to
support old Rubies.
=> gemspec: lock rack-test to v0.7.0

CHANGELOG.md, lib/airbrake/rails.rb
We have a product where we do not use ActiveRecord, however a gem is loading up active_record/errors.rb so it can handle errors for when a product does use AR.   This causes airbrake to incorrectly detect that activerecord is loaded and it blows up as the ConnectionAdapter code isn't actually loaded.  This extends the current check so that it better handles this scenario.
Related to #580
=> Better handle detecting if ActiveRecord is actually loaded

Appraisals, gemfiles/rails_3.2.gemfile, gemfiles/rails_edge.gemfile, gemfiles/sinatra.gemfile
For some reason it was resolving to 6.0.0.alpha, and as of now I can't find
where it is being mentioned in the latest repo. Either way, it's too early to
think about it because even v5.2.0 hasn't been released yet.
=> Appraisals: point rails-edge to the 5-2-stable branch

README.md, lib/airbrake/sidekiq.rb, lib/airbrake/sidekiq/retryable_jobs_filter.rb, spec/unit/sidekiq/retryable_jobs_filter_spec.rb
With this filter, errors from jobs tha will be retried will be ignored and only collected when Sidekiq exhausts its retries attempts
Closes #830
=> Add a filter that ignore retryable Sidekiq jobs

.rubocop.yml, Gemfile, lib/generators/airbrake_generator.rb
* rubocop: disable the Bundle/OrderedGems cop
This cop is nothing but a nitpick. Following its rules doesn't give anything but
headache, thus I'm disabling it.
* rubocop: disable the Naming/UncommunicativeMethodParamName cop
This rule is a little annoying to follow. Although I understand that it
prevents you from bad variable names, sometimes they are useful (for example,
`h` or `th`).
* rubocop: ignore gemfiles for the Style/SymbolArray cop
Those gemfiles are autogenerated and it is not recommended to edit them by hand.
=> Gemfile: update rubocop to v0.55.0

lib/airbrake/delayed_job.rb, lib/airbrake/logger.rb, lib/airbrake/rack/context_filter.rb, lib/airbrake/rack/http_headers_filter.rb, lib/airbrake/rack/http_params_filter.rb, lib/airbrake/rack/middleware.rb, lib/airbrake/rack/request_body_filter.rb, lib/airbrake/rack/session_filter.rb, lib/airbrake/rack/user.rb, lib/airbrake/rails.rb, lib/airbrake/rails/action_controller.rb, lib/airbrake/rails/active_job.rb, lib/airbrake/rails/active_record.rb, lib/airbrake/rake.rb, lib/airbrake/resque.rb, lib/airbrake/shoryuken.rb, lib/airbrake/sidekiq.rb, lib/airbrake/sidekiq/retryable_jobs_filter.rb, lib/airbrake/sneakers.rb, lib/airbrake/version.rb, lib/generators/airbrake_generator.rb
YARD sometimes doesn't understand `##`, since it's actually RDoc's format. We
use YARD in this project so we should try to follow its conventions instead.
=> Stop following the RDoc convention

CHANGELOG.md, lib/airbrake/rack/context_filter.rb
There was a bug where the integration would attach a frozen hash, then
`DependencyFilter` from airbrake-ruby would try to add more data to the hash but
couldn't due to the `can't modify frozen Hash` error. We shoudn't freeze public
hashes.
=> rack/context_filter: don't freeze the versions hash

CHANGELOG.md, lib/airbrake/sneakers.rb, spec/unit/sneakers_spec.rb
Fixes #850
("Stack level is too deep" on 7.3.3 when calling from Sneakers (7.2.0) worker
with Rails 5.2.0)
`as_json` causes problems on certain objects that Sneakers manages. We can't do
anything but ignore them.
=> sneakers: fix SystemStackError

.circleci/config.yml
It looks like with the new JRuby release the old CircleCI image is not available
anymore.
=> circleci: fix JRuby build

CHANGELOG.md, lib/airbrake/rails/active_job.rb, lib/airbrake/rake.rb
We shouldn't overwrite 'params' because it breaks filters, such as
`ContextFilter`, making `Airbrake.merge_context` unusable for these
integrations.
=> rails/active_job,rake: don't overwrite 'params'

README.md
=> README: remove the Travis badge

.circleci/config.yml, .circleci/ruby-2.0.0p648-airbrake/Dockerfile
CircleCI doesn't host Ruby 2.0 anymore but we still support it. We've been
hosting the custom image for several months but DockerHub doesn't display the
Dockerfile used. I am committing it here so it's not lost.
=> circleci: commit Dockerfile for Ruby 2.0.0

CHANGELOG.md, lib/airbrake/rack/middleware.rb, spec/integration/rails/rails_spec.rb
There was a bug where status code is reported as 0 for routes that raise
exceptions. Typically, the expected code should be 500. This is because the
Rails hook needs extra handling in this case. The approach is taken from
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/log_subscriber.rb
=> rack/middleware(rails): support route status codes with exceptions

.rubocop.yml, lib/airbrake/rack/middleware.rb, spec/integration/rails/rails_spec.rb
When `ActionDispatch::ExceptionWrapper` fails to return a code for an exception,
then it returns 0. This confuses our backend, so we should convert that into 500
as the most reasonable default value.
=> rack/middleware: default to 500 instead of 0 if code can't be found

lib/generators/airbrake_initializer.rb.erb
per https://github.com/rubocop-hq/ruby-style-guide#percent-literal-braces, `%w` arrays should be delimited by `[]` instead of `()`
=> Update initializer erb to conform to rubocop style guide

airbrake.gemspec
We still want to test on Ruby 2.2 but Nokogiri doesn't support it anymore.
=> gemspec: lock nokogiri to 1.9.1

lib/airbrake/rack/middleware.rb, lib/airbrake/rails.rb, lib/airbrake/rails/action_controller_subscriber.rb
I hadn't known that Rails hooks can accept classes. This new way provides better
separation of concerns, so the middleware class is not polluted with route
stats stuff.
=> rack/middleware: factor out Rails subscriber to a separate file

airbrake.gemspec, spec/spec_helper.rb
=> gemspec: depend on airbrake-ruby `~> 3.0`

lib/airbrake/rack.rb, lib/airbrake/rack/context_filter.rb, lib/airbrake/rack/middleware.rb, lib/airbrake/rack/user_filter.rb, spec/unit/rack/context_filter_spec.rb, spec/unit/rack/http_headers_filter_spec.rb, spec/unit/rack/http_params_filter_spec.rb, spec/unit/rack/request_body_filter_spec.rb, spec/unit/rack/session_filter_spec.rb, spec/unit/rack/user_filter_spec.rb
In order to give more control over how to find the current user and what
information to include in the payload, allow defining a class for the
rack middleware to use when extracting the current user payload from
the rack request.
=> rack/middleware: move user extraction logic to its own filter

CHANGELOG.md, lib/airbrake/rack/middleware.rb
Fixes https://github.com/airbrake/airbrake/pull/892#issuecomment-463267205.
Rails ships with the `-O` switch, which disables ActiveRecord. We hook into
ActiveRecord when Rails is present, so it causes breakage for such apps.
Now we are smarter and don't add any SQL hooks when ActiveRecord is not present.
=> rack/middleware: don't install ActiveRecord hooks when it's absent

CHANGELOG.md, lib/airbrake/rack/middleware.rb, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/active_record_subscriber.rb
Using thread locals was not a reliable approach. While local testing was showing
that subscribers share information, in production it didn't really work. It
could be the order of subscribers, or something else (hard to tell).
This change removes the need for thread locals and uses a shared object.
=> rack/middleware: fix performance stat sending

CHANGELOG.md, lib/airbrake/logger.rb, spec/unit/logger_spec.rb
There was a bug where provided logger has severity ERROR but `airbrake_level`
would still be WARN (because it was hardcoded). Because of this WARN messages
would be sent to Airbrake, even though nothing would be logged.
Additionally, if you change level of the wrapped logger, airbrake_level would
get out of sync.
=> logger: respect level of the logger that we wrap

lib/airbrake/rack/middleware.rb, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/active_record_subscriber.rb, spec/unit/rack/middleware_spec.rb
The old system serves no purpose since `Airbrake` is a global wrapper used in
every integration.
=> Cleanup Rack & Rails integrations from notifier leftovers

lib/airbrake/rake.rb, spec/apps/rails/dummy_task.rake, spec/integration/rails/rake_spec.rb, spec/spec_helper.rb, spec/support/matchers/a_notice_with.rb
* Added `a_notice_with` matcher to help readability
* Used mocks instead of making HTTP requests
* Deleted the 'minimal' task - the tests for it were very brittle
=> rake: refactor specs with help of mocks

airbrake.gemspec
While upgrading, I noticed some tests are failing. Not sure why, so I decided to give them another though. Using mocks seemed to be a brilliant idea:
* these tests are faster by order of magnitude
* we no longer pry into low-level details such as HTTP calls. This layer is
tested in airbrake-ruby
=> gemspec: bump airbrake-ruby to `~> 4.1.0`

lib/airbrake/rack/context_filter.rb, lib/airbrake/rack/middleware.rb, lib/airbrake/rails.rb, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/active_record_subscriber.rb
It was necessary to keep the hooks inside the middleware to support multiple
notifiers. Since we don't support this feautre anymore, we are feeling more
relaxed and can simplify the middleware. It was a horrible hack anyway, since we
had to have guards in `#initialize` and I'm glad it's going away.
`require` guarantees that we load the file only once, so it's safe to add
filters in the top level. We require these files from the railtie, and it also
inadvertently fixes #909 (NameError: uninitialized constant Airbrake::Rails).
=> rack/middleware: factor out hook installation code outside class

CHANGELOG.md, lib/airbrake/rails/active_record_subscriber.rb, spec/integration/rails/rails_spec.rb
If for whatever reason `caller` doesn't return anything, we shouldn't crash.
=> rails/active_record_subscriber: handle `nil` frames

lib/airbrake/rails.rb
If ActiveRecord has not been defined, loading ActiveRecordSubscriber will fail because of its call to ActiveRecord::Base.
Chose to add the guard clause to [lib/airbrake/rails.rb](https://github.com/airbrake/airbrake/blob/b21502812f7da58a8a3c508108c6a574cf1659f0/lib/airbrake/rails.rb) instead of to [airbrake/rails/active_record_subscriber](https://github.com/airbrake/airbrake/blob/b21502812f7da58a8a3c508108c6a574cf1659f0/lib/airbrake/rails/active_record_subscriber.rb), since that class name implies ActiveRecord is already available.
You can see a guard clause [used to exist](https://github.com/airbrake/airbrake/commit/4e5628f680aede2aeca5e422ccf54fca38fde8d8#diff-e09b896e9abbe09861d7846819a7bd56L32), but the code it referenced was removed and added into …
=> Reintroduce ActiveRecord guard clause

CHANGELOG.md, lib/airbrake/rails.rb, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, spec/integration/rails/rails_spec.rb
This subscriber sends performance breakdown information to Airbrake. It sends
database and view performance info.
=> Add ActionControllerPerformanceBreakdownSubscriber

CHANGELOG.md, lib/airbrake/rails.rb, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb
Apparentlty, Rails sometimes doesn't set these values for an event. When that
happens, Airbrake Ruby chokes because it doesn't expect `nil` :/
Additionally, to prevent nasty bugs from occurring in the future I added some
unit tests (should've been added from the very beginning TBH).
=> rails/breakdown_subscriber: pass 0 instead of nil for db/view values

spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb
Setting nil leaves the `routes` key, which is violating the clean state
principle.
=> spec/unit/rails/breakdown_subscriber: cleanup properly

CHANGELOG.md, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb
`.to_i` converts Float numbers to Integer and we actually want Floats to reflect
metrics more accurately.
=> rails/breakdown_subscriber: maintain precision

CHANGELOG.md, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, spec/apps/rails/dummy_app.rb, spec/integration/rails/rails_spec.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb
The backend rejects performance breakdown if one of the groups is 0 with this
message: `routes: sum <= 0`.
Not every route executes database requests, therefore, many routes won't have a
chance to send their `view` data.
=> Fix performance breakdown not being sent when a group has 0 value

CHANGELOG.md, lib/airbrake/rack/route_filter.rb, spec/unit/rack/route_filter_spec.rb
Fixes airbrake/airbrake-ruby#457
(request.env['sinatra.route'] is nil)
The error occurs when a route is not defined (404).
=> rack/route_filter: don't crash when no Sinatra route is available

CHANGELOG.md, README.md, lib/airbrake/rack.rb, lib/airbrake/rack/middleware.rb, lib/airbrake/rails.rb, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/active_record_subscriber.rb, spec/apps/rack/dummy_app.rb, spec/apps/sinatra/sinatra_test_app.rb, spec/unit/rack/middleware_spec.rb
We load these hooks unnecessarily for those customers who don't use performance
stats. It may cause an unwanted overhead for them: we spend CPU time collecting
info but never send it. In this commit we check if performance_stats is enabled
and include the hooks only if it is.
=> rails: load performance hooks only if performance_stats is enabled

airbrake.gemspec
Fixes #941 ([REQUEST] Start depending on airbrake-ruby 4.2.2?)
=> gemspec: bump airbrake-ruby to '~> 4.2'

CHANGELOG.md, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb
Some routes can return both `*/*` and `:html` response types. I did some
googling and uncovered that `*/*` means `:html`. Due to historical reasons Rails
cannot change it: https://github.com/rails/rails/issues/8987
Currently, we display both `*/*` and `html`, which is clearly confusing. By
merging them together we will treat `*/*` as HTML.
=> action_controller_performance_breakdown: treat */* as :html

lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/active_record_subscriber.rb, lib/airbrake/rails/backtrace_cleaner.rb, lib/airbrake/rails/event.rb, spec/apps/rails/dummy_app.rb, spec/integration/rails/rails_spec.rb, spec/unit/rails/action_controller_notify_subscriber_spec.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb, spec/unit/rails/action_controller_route_subscriber_spec.rb, spec/unit/rails/active_record_subscriber_spec.rb
Continuing work started in https://github.com/airbrake/airbrake/pull/953.
`Airbrake::Rails::Event` turns out to be a good idea because it encapsulates a
lot of related logic together (previously it was scattered all around hooks).
=> rails: add unit tests for hooks

CHANGELOG.md, lib/airbrake/rails.rb, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/net_http.rb, spec/apps/rails/dummy_app.rb, spec/integration/rails/rails_spec.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb, spec/unit/rails/action_controller_route_subscriber_spec.rb
We currently integrate only with `Net::HTTP` since it's the most popular HTTP
library for Ruby.
=> rails: add HTTP breakdown

CHANGELOG.md, README.md, lib/airbrake/rack.rb, lib/airbrake/rack/instrumentable.rb, lib/airbrake/rails/curb.rb, lib/airbrake/rails/http.rb, lib/airbrake/rails/http_client.rb, lib/airbrake/rails/net_http.rb, lib/airbrake/rails/typhoeus.rb, spec/unit/rack/instrumentable_spec.rb, spec/unit/rack/rack_spec.rb
The new `Airbrake::Rack::Instrumentable` module adds
`airbrake_capture_timing`. This method expects the name of the method to
instrument. When such a method is called, Airbrake measures its timing and sends
the stats to Airbrake. The stats will be displayed in the performance breakdown
view of a route. Routes are determined automatically.
```ruby
class UsersController
extend Airbrake::Rack::Instrumentable
def index
end
airbrake_capture_timing :index
end
```
Alternatively, you can measure performance within a method:
```ruby
def index
Airbrake::Rack.capture_timing('operation name') do
do_measured_stuff
end
do_other_stuff
end
```
=> rails,rack: add the ability to send performance breakdown manually

CHANGELOG.md, lib/airbrake/rack/instrumentable.rb, spec/unit/rack/instrumentable_spec.rb
This functionality is useful when you want to decouple your Airbrake dashboard
and your code from each other. For example, if you instrument a method called
"do_http()", you'd rather instrument it under the "HTTP" label, so it looks more
concise. Use cases are endless.
=> rack/instrumentable: add the ability to set custom label

CHANGELOG.md, lib/airbrake/rack/middleware.rb, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, spec/integration/rails/rails_spec.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb
Request & User are attached to every resource the subscriber sends (if
available). It is attached to the resource's stash. The stash is accessible from
performance filters. Example:
```ruby
Airbrake.add_performance_hook do |resource|
if resource.stash.key?(:user)
end
end
=> rails/performance_breakdown_subscriber: attach request & user

airbrake.gemspec
Fixes #970 (Spec logs are included in gem builds)
Looks like this option serves no real purpose. It's only there for backwards
comatibility. More info: https://github.com/rubygems/rubygems/issues/735
=> gemspec: don't specify test_files

CHANGELOG.md, lib/airbrake/rack/middleware.rb, spec/unit/rack/middleware_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/976#issuecomment-499064689
We clear too soon, so "framework" exceptions never have attached requests.
=> rack/middleware: keep rack request until we're done reporting

lib/airbrake/sidekiq/retryable_jobs_filter.rb, spec/unit/sidekiq/retryable_jobs_filter_spec.rb
It seems Sidekiq must have modified behaviour this filter relies on in recent versions. The existing code fails in two conditions:
1) When `job['retry_count']` is nil, which happens the first time a job fails. (There is no nil check.)
2) When `job['retry_count']` is not nil, the number represent how many retries have *already* been attempted. We must add 1 to this number, or `retry_count` will *always* be lower than `max_attempts`, even on the final retry when we want to actually notify.
=> Fix broken retry count logic in Sidekiq RetryableJobsFilter

CHANGELOG.md, airbrake.gemspec
This enables performance stats by default.
=> gemspec: bump airbrake-ruby to `~> 4.5`

Appraisals, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile, gemfiles/rails_5.2.gemfile
i18n doesn't support Rubies below 2.3 anymore:
https://github.com/ruby-i18n/i18n/commit/213641fe9a0c8f59c5b7d57b2e437d9cf4cfc825
=> Appraisals: lock i18n to 1.5 on modern Rubies

lib/airbrake/sidekiq/retryable_jobs_filter.rb, spec/unit/sidekiq/retryable_jobs_filter_spec.rb
This is useful if we don't want to be spammed by a couple of retries,
but *do* want repeated warnings if a job continues to fail multiple
times.
=> Add option to notify of sidekiq retries after a given number

CHANGELOG.md, README.md, lib/generators/airbrake_initializer.rb.erb
With [`performance_stats = true`][1] Airbrake generates a lot of logs now. This
causes some inconvenience in the development environment because Rails uses
`debug` severity for its logger.
We don't have a lot of places where we log but we do log frequently (on every
request we log performance data for that request). Simply removing that debug
output would solve the issue but we need it so we can debug the library.
The best decision would be using a separate file, where we can be noisy without
annoying our users. If we ever need that debug output, we can ask the users to
check `airbrake.log`.
---
* generators/airbrake_initializer: support RAILS_LOG_TO_STDOUT 
`RAILS_LOG_TO_STDOUT` was added in rails/rails@4a836dc
This variable is pretty much self-documenting, so all I have to say is that …
=> Rails: log to airbrake.log from now on

lib/generators/airbrake_initializer.rb.erb
When I ran Rubocop Rails cops against this file, it showed me a warning and
suggested to use `Rails.root.join`. We want to be compatible with that since
people who use Rubocop in their apps will likely complain about this.
=> generators/airbrake_initializer: be Rubocop Rails compatible

CHANGELOG.md, airbrake.gemspec, lib/airbrake/rails.rb, spec/spec_helper.rb
Likely fixes:
* #994 (Memory usage)
* #990 (Add support for Rails engine route prefixes)
More details in airbrake/airbrake-ruby#495. In short,
this disables SQL query collection by default and allows enabling it only for
certain accounts.
=> rails: install the ActiveRecord hook only when `query_stats = true`

CHANGELOG.md, lib/airbrake/rails/app.rb
Fixes #988 (Add support for Rails engine route prefixes)
=> rails/app: detect and attach engine name to routes

lib/airbrake/rails/event.rb
This is going to be helpful in troubleshooting #991.
(Airbrake: got status_code=0, wanted >=200 and <600)
I am currently not sure why this happens and I hope to collect more debug
information.
=> rails/event: log zero status codes

CHANGELOG.md, lib/airbrake/rails/event.rb
Fixes #991 (Airbrake: got status_code=0, wanted >=200 and <600)
The ActiveSupport event doesn't have status only in two cases:
- an exception was thrown
- unauthorized access
We have already handled the exception so what's left is unauthorized
access. There's no way to know for sure it's unauthorized access, so
we are rather optimistic here.
=> rails/event: report unauthorized access routes as 401 instead of 0

Appraisals
i18n doesn't support Ruby 2.2 but we still do. Our build has started failing
because of this: https://circleci.com/gh/airbrake/airbrake/6226
=> Appraisals: lock i18n to '~> 1.4'

CHANGELOG.md, README.md, lib/airbrake/rails.rb, lib/airbrake/rails/railtie.rb, lib/generators/airbrake_initializer.rb.erb
The new suggested way to configure logger in Rails apps was added in pull
request #986. Unfortunately, there's an issue with it. We load the initialiser
on `bundle exec rake airbrake:deploy` and at this time `Rails.logger` is not
defined yet. Therefore, the deploys would fail in 100% of cases because of
NoMethodError.
To work around this issue we simply check for the existence of `Rails.logger`.
This change is simple. However, what I don't like is that we leak a lot of *our*
code to the user space. The users have to study how we setup logging. For the
sake of simplicity we want to avoid that and keep the config simple.
To achieve that, `Airbrake::Rails.logger` was added. It hides all the complexity
from the users. Probably the best part is that if users stumble upon another bug
in the …
=> rails: fix broken 'airbrake:deploy'

.circleci/config.yml, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile, gemfiles/rails_5.2.gemfile
Looks like we forgot to include the Rails 5.0 step.
Note that we don't test on JRuby because of a bug in activerecrod-jdbc-adapter.
https://github.com/jruby/activerecord-jdbc-adapter/issues/700
=> circle: actually test against Rails 5.0

.circleci/config.yml, Appraisals, gemfiles/rails_4.1.gemfile
It turns out some customers still use Rails v4.1. I decided to add it back to
the build matrix, so that we can be sure we still support it. We are not
building it on JRuby, 2.6 and 2.4 due to segfaults. It's not really worth
spending time on figuring out why it happens, since other Rubies pass just
fine.
=> circle: test Rails v4.1

CHANGELOG.md, lib/airbrake/rails/action_controller.rb
Fixes #1008 (Helpers should pass provided blocks on to Airbrake.notify)
=> rails/action_controller: pass block along with standard arguments

lib/airbrake/rails/action_controller_route_subscriber.rb
The `memory_profiler` gem reports that Ruby allocates 22.6 Kb just for the
'controller' string. Since this code path is critical, we want to squeeze out
the best performance we can achieve. Making the keys constant reduces
allocations to zero.
=> rails/action_controller_route_subscriber: reduce allocations

airbrake.gemspec
Newer minitest dropped support for Ruby 2.2 that we still support.
=> gemspec: lock minitest to v5.11.3

CHANGELOG.md, lib/airbrake/rails/railtie.rb
I noticed that in a Rails 5 app a controller hook gets executed twice, passing
the same route. Googling revealed that there's a new option called `run_once` to
prevent addition of multiple hooks of the same type:
https://github.com/rails/rails/issues/31041
=> rails/railtie: use run_once for on_load

Appraisals, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile
Sprockets 4.0 requires Ruby 2.5+, which is way too radical for us.
=> gemspec: lock sprockets to '~> 3.7'

airbrake.gemspec
Fixes https://circleci.com/gh/airbrake/airbrake/6688
Newer versions dropped support for Ruby 2.2 and less.
=> gemspec: depend on rack-cache 1.9.0

CHANGELOG.md, lib/airbrake/rails/railtie.rb, spec/integration/rails/rails_spec.rb
Fixes #1021 (Patch for Active Record < 4.2 causes unexpected behaviour on Rails
>= 5.1)
=> rails/railtie: do not include the `after_commit` patch on Rails 5+

CHANGELOG.md, lib/airbrake/rack/route_filter.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/app.rb, spec/unit/rails/action_controller_route_subscriber_spec.rb
The library uses two different ways for route identification:
* the first way is to use Rails' `recognize` API (used in `Rack::RouteFilter`)
* the second way is to compare controller and action
(used in `ActionControllerRouteSubscriber`)
This approach causes troubles for apps that define routes the following way:
```
get '/billing/edit', to: 'accounts#edit'
```
`Rack::RouteFilter` would find route `/account/edit` while
`ActionControllerRouteSubscriber` would find `/billing/edit`.
This is unwanted because Airbrake will think these are two separate routes while
in reality it's the same route (just aliased).
In this fix we unify the approach of route identification and use a more stable
API provided by Rails ("recognize"). The additional benefit is that we no longer
need to worry about …
=> action_controller_route_subscriber: use "recognize" to find routes

CHANGELOG.md, lib/airbrake/rack/route_filter.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/app.rb, spec/unit/rails/action_controller_route_subscriber_spec.rb
v9.5.1 introduced a bug where engine routes would not be recognised
anymore. This is because the new algorithm for route finding doesn't query
cached routes anymore. Instead, it relies on Rails APIs, which don't provide
enigne by default. With a bit of tinkering we can restore engine support again.
=> action_controller_route_subscriber: fix support for engine routes

CHANGELOG.md, lib/airbrake/rack/route_filter.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/app.rb, spec/unit/rails/action_controller_route_subscriber_spec.rb
By returning nil explicitly we make sure that the code will not blow up in the
future if Rails' `recognize` decides to return something other than a
route (which happened to me locally on Rails 5 while I was testing something).
Additionaly, we return our own Route now (again), so that we don't leak Rails
code all over our codebase.
=> rails/app: return nil when request is unrecognized

CHANGELOG.md, lib/airbrake/rails/app.rb
It turns out Rails can strip `request.path_info` from the given request. This is
an unexpected mutation, which we work around by duplicating the object.
For example:
```
request.path_info #=> "/"
::Rails.application.routes.router.recognize(request) {}
request.path_info #=> ""
```
This issue can break Rails engine route links. For example, `users_path` inside
an engine is expected to be `/admin/users`, however because of the mutation it
becomes just `/users`.
=> rails/app: duplicate request before recognising

CHANGELOG.md, lib/airbrake/rack/context_filter.rb, spec/unit/rack/context_filter_spec.rb
Since we want to report the client IP, we should be using `#remote_ip` instead
of `#ip`.
The difference between the two is explained in
https://stackoverflow.com/q/10997005/511205
> `request.ip` returns the client ip even if that client is a proxy.
>
> `request.remote_ip` is smarter and gets the actual client ip. This can only be
done if the all the proxies along the way set the X-Forwarded-For header.
=> rack/context_filter: use #remote_ip instead of #ip

lib/airbrake/sneakers.rb
Note: we should migrate to the middleware API once it's released (probably in
v2.12.0):
https://github.com/jondot/sneakers/pull/364
=> sneakers: send job execution statistics

CHANGELOG.md, lib/airbrake/resque.rb
With `airbrake-ruby` v4.11.0 we can now send `:timing`, which is the correct way
to call `notify_queue`. Here we update the code to the new API and also fix
timing reporting, which was actually broken before.
=> resque: send proper timing for job execution

Appraisals
CircleCI pulls Ruby 2.2.0 but we expect 2.2.2. Because of this the i18n lock to
1.4 has no effect and it makes the build fail:
https://circleci.com/gh/airbrake/airbrake/7325
=> Appraisals: fix build on Ruby 2.2.0

CHANGELOG.md, lib/airbrake/sneakers.rb
With `airbrake-ruby` v4.11.0 we can now send `:timing`, which is the correct way
to call `notify_queue`.
=> sneakers: update API for job execution timing

CHANGELOG.md, lib/airbrake/delayed_job.rb
With `airbrake-ruby` v4.11.0 we can now send `:timing`, which is the correct way
to call `notify_queue`.
=> delayed_job: update API for job execution timing

lib/airbrake/sidekiq.rb, spec/unit/sidekiq_spec.rb
With `airbrake-ruby` v4.11.0 we can now send `:timing`, which is the correct way
to call `notify_queue`.
=> sidekiq: update API for job execution timing

CHANGELOG.md, lib/airbrake/rails/app.rb
`Rails.application.router.routes.recognize` does not return expected results
when a request is made to an engine. For example, if we have `Marketing::Engine`
and make a request to its route `/pricing`, the call would find this path:
`marketing#/`. Instead, it should be `marketing#pricing`.
In order to fix that issue we must ask every engine separately and call
`recognize` on every engine's routes. This method is supposedly slower but much
more reliable.
=> rails/app: fix engine route reporting

CHANGELOG.md, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, lib/airbrake/rails/active_record_subscriber.rb, lib/airbrake/rails/event.rb, spec/unit/rails/action_controller_notify_subscriber_spec.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb, spec/unit/rails/active_record_subscriber_spec.rb
Resolves https://github.com/airbrake/airbrake-ruby/issues/532
(Airbrake performance changes are filling logs with deprecation messages)
This was inroduced by https://github.com/airbrake/airbrake-ruby/pull/526
We can now pass `event.duration`, so there's no need to calculate it again. This
is more accurate as well since we pass monotonic time instead of realtime.
=> Fix deprecation warnings about `:start_time` & `:end_time`

.gitignore
Make local development easier for rvm and rbenv users.
I know .rbenv-version and .rvmrc are already ignored, but neither of
those files are recommended for use. Good to ignore the portable ones.
=> Ignore .ruby-version and .ruby-gemset

CHANGELOG.md, lib/airbrake/rails/railtie.rb
Fixes #1057 (Airbrake 9.5.5 update Error: config.query_stats = false is not
working)
=> rails/railtie: run airbrake.middleware after config initializers

lib/airbrake/sneakers.rb
The Sneakers::ErrorReporter worker_error method context_hash parameter
is Hash data, not keyword parameters. Declare our handler accordingly.
=> Fix keyword argument error in Sneakers integration

lib/airbrake/rack/instrumentable.rb, spec/unit/rack/instrumentable_spec.rb
- Now supports wrapping the target method with alias_method_chain style
or Module prepend style. Which one you should use depends on whether
the method you're wrapping is chained or prepended already.
- Prevents you from wrapping a method more than once in chain mode,
because that leads to stack overflows.
- Can handle method names ending in "?", "!", or "=".
- Can wrap operator methods (in prepend mode, at least).
- Uses Ruby 2.7+ style method forwarding when that's supported.
- Defines the wrappers using module_eval so we don't have closure
references left in memory.
[Fixes #1062]
=> Enhancements to airbrake_capture_timing

Appraisals, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile
Rack 2.1.2+ dropped support for Ruby 2.2 and below:
https://github.com/rack/rack/commit/d81a5d3bdd20d80527164705b1fcfd0b7f4be6cd
=> Appraisals: lock Rack to 2.1.2 on Rails 5+

CHANGELOG.md, lib/airbrake/rails/active_job.rb
It appears that our ActiveJob integration refuses to report errors if it's
configured in pair with Resque, DelayedJob or Sidekiq.
This code I am removing was introduced in #789. Now, 2.5 years later when I read
it, it doesn't make any sense to me. The errors are not reportred because we
explicitly guard against it.
The code is supposed to protect against the situation when we report the same
error twice (through the integration such as DelayedJob and through
ActiveJob). However after extensive testing I couldn't confirm anymore that if
this guard is removed, we report twice. I was able to confirm that we report
only once, through the ActiveJob integration.
=> rails/active_job: allow ActiveJob errors to be reported

CHANGELOG.md, lib/airbrake/rails/net_http.rb
Fixes #1077 (Airbrake's new Performance metrics instrumentation leads to
infinite loop with Datadog)
our implementation (unless they forget to call `super`) and we will also respect
other libraries that monkey-patch `Net::HTTP#request`.
=> rails/net_http: monkey-patch with prepend instead of method chaining

.circleci/config.yml
Kindly reported by
https://app.circleci.com/pipelines/github/airbrake/airbrake/1/workflows/368850c2-3062-4634-afe4-890fbebd088c/jobs/8116
```
#!/bin/sh -eo pipefail
```
=> circleci: fix typo in rails60 directive

CHANGELOG.md, lib/airbrake/rails/backtrace_cleaner.rb
Since we rely on Rails' BacktraceCleaner to find function/file/line of the
executed SQL, sometimes the backtrace to clean can contain frames coming from
this library.
Namely, `active_record_subscriber.rb` will be returned if an SQL request is
coming from a Rails engine. In order to avoid that, we silence ourselves, so
that the cleaner can proceed to the next line and find the correct call-site
down the stack.
=> rails/backtrace_cleaner: silence own frames

CHANGELOG.md, lib/airbrake/delayed_job.rb, lib/airbrake/rails/active_job.rb
Fixes #1081 (delayed_job performance issues with Airbrake version 10.0.1)
There's no good reason to use synchronous delivery. I tested DJ on a sample app
with this change and stat reporting still works, while job execution time is
1000% faster.
=> delayed_job: send execution stats asynchronously

CHANGELOG.md, lib/airbrake/rails/app.rb
Fixes #1091 (Performance - all routes appear as / with 10.0.3. Works fine in
9.5.5)
When using Rails' `recognize`, catch-all routes have higher precedence than real
routes. By skipping catch-all routes we can fall through to the next route,
which appears to be a real route.
One gotcha is that the API we use to check for "catch-all" routes is not
available on Rails 4.1 and lower (only Rails 4.2+).
=> rails/app: ignore "catch-all" routes

airbrake.gemspec
Newest version of appraisal and ffi dropped support for Ruby <= 2.2, but we still support them.
=> Lock ffi and appraisal

CHANGELOG.md, lib/airbrake/rails/railtie.rb
Fixes #1097 (Railtie deprecation for connection_config)
=> rails/railtie: fix deprecation warning about 'connection_config'

CHANGELOG.md, lib/airbrake/sidekiq.rb, spec/unit/sidekiq_spec.rb
Fixes #1102
(Airbrake::Sidekiq::RetryableJobsFilter not working)
`Airbrake::Sidekiq::RetryableJobsFilter` checks for `notice[:params][:job]` and
then reads job-specific keys. However our Sidekiq integration places
job-specific keys to `notice[:params]`. Therefore, the filter's code always
thinks that the job is not retryable and never ignores the notice.
=> sidekiq: specify that params are 'job' params

CHANGELOG.md, lib/airbrake/rails/app.rb
Fixes #1072 (request.path starts with "//" after updating to v10)
This is a hack but we have no better option since `request.dup` is not able to
duplicate `script_name` properly.
=> rails/app: fix request.path with "//"

CHANGELOG.md, lib/airbrake/rack.rb, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/action_controller_performance_breakdown_subscriber.rb, lib/airbrake/rails/action_controller_route_subscriber.rb, lib/airbrake/rails/active_record_subscriber.rb, lib/airbrake/rails/excon_subscriber.rb, lib/airbrake/rails/railtie.rb, spec/integration/rails/rails_spec.rb, spec/integration/rails/rake_spec.rb, spec/unit/rack/rack_spec.rb, spec/unit/rails/action_controller_notify_subscriber_spec.rb, spec/unit/rails/action_controller_performance_breakdown_subscriber_spec.rb, spec/unit/rails/action_controller_route_subscriber_spec.rb, spec/unit/rails/active_record_subscriber_spec.rb, spec/unit/rails/excon_spec.rb
Previously, we were installing performance hooks based on the value from the
Airbrake config. If `performance_stats` is `true`, then the hooks will be
installed during initialization, if it's `false`, the hooks would never be
installed.
Now, `airbrake-ruby` supports remote configuration, which can change the value
of `performance_stats` at runtime. In order to support this feature we must
change the approach and install the hooks in either case. The
`performance_stats` check is now performed inside the hooks, since this will
allow us to enable/disable the feature during the runtime.
A pleasant effect of this change is that we no longer need to read the config
inside our railtie. This fixes #1105, which reports an issue with our existing
code where we hook into `after: …
=> rails: install all performance hooks by default

spec/spec_helper.rb
This somehow fixes failing builds:
https://app.circleci.com/pipelines/github/airbrake/airbrake/127/workflows/d65e52ce-08da-4345-b6dc-ba568b8f85a7/jobs/9045
> Real HTTP connections are disabled. Unregistered request:
> GET https://v1-production-notifier-configs
=> spec_helper: set remote_config_host to nil

lib/airbrake/rails.rb
rake airbrake:deploy crashes when environment variable RAILS_LOG_TO_STDOUT is present:
```
NoMethodError: undefined method `level' for nil:NilClass
/usr/local/bundle/ruby/2.5.0/gems/airbrake-11.0.0/lib/airbrake/rails.rb:10:in `logger'
/service/config/initializers/airbrake.rb:30:in `block in <top (required)>'
/usr/local/bundle/ruby/2.5.0/gems/airbrake-ruby-5.0.2/lib/airbrake-ruby.rb:122:in `configure'
/service/config/initializers/airbrake.rb:12:in `<top (required)>'
```
This problem has already been fixed before but only for the case when RAILS_LOG_TO_STDOUT is not present.
My fix moves the earlier fix for level: out of its else-branch. It's now effective independend of RAILS_LOG_TO_STDOUT. A ::Rails.logger is nil in rake airbrake::deploy and this doesn't dependend on RAILS_LOG_TO_STDOUT. …
=> Fix crash when airbrake:deploy used with RAILS_LOG_TO_STDOUT

CHANGELOG.md, airbrake.gemspec, spec/spec_helper.rb
With airbrake-ruby 5.1 we can now set `environment` to `test` in our test
suite. This will disable the notifier config feature, and thus the proper way to
turn it off.
=> gemspec: bump airbrake-ruby to `~> 5.1`

airbrake.gemspec
v0.13.0 fails with:
```
RuntimeError:
Compilation error generating constants :
sh: 1: gcc: not found
```
https://app.circleci.com/pipelines/github/airbrake/airbrake/158/workflows/f22d902f-f0bb-449b-8b95-2a0ac76047f2/jobs/9248
=> gemspec: lock "ethon" to v0.12.0

CHANGELOG.md, lib/airbrake/rails/http.rb
Fixes #1161 (missing prepend instrumentation leads to stack level too deep
error)
Since we don't care about Ruby 1.9 support,  we can safely rely on `prepend` to
our implementation (unless they forget to call `super`) and we will also respect
other libraries that monkey-patch `HTTP::Client#perform`.
=> rails/http: monkey-patch with prepend instead of method chaining

CHANGELOG.md, lib/airbrake/sneakers.rb
our implementation (unless they forget to call `super`) and we will also respect
other libraries that monkey-patch `Sneakers::Worker#process_work`.
=> sneakers: monkey-patch with prepend instead of method chaining

CHANGELOG.md, lib/airbrake/rails/action_cable.rb
our implementation (unless they forget to call super) and we will also respect
other libraries that monkey-patch `ActionCable::Channel::Base#perform_action`.
=> action_cable: monkey-patch with prepend instead of method chaining

CHANGELOG.md, lib/airbrake/resque.rb
our implementation (unless they forget to call super) and we will also respect
other libraries that monkey-patch `Resque::Job#perform`.
=> resque: monkey-patch with prepend instead of method chaining

CHANGELOG.md, lib/airbrake/rake.rb
our implementation (unless they forget to call super) and we will also respect
other libraries that monkey-patch `Rake::Task#execute`.
=> rake: monkey-patch with prepend instead of method chaining

airbrake.gemspec
We no longer need this lock since the build passes fine without it.
=> gemspec: remove ethon dependency lock

spec/integration/rails/rails_spec.rb
This spec segfaults on latest JRuby 9.2.19.0 in JVM.
https://app.circleci.com/pipelines/github/airbrake/airbrake/227/workflows/3db05cae-87d8-4599-9da2-a37c4c76bf4f/jobs/9670
During an extensive debugging session I haven't been able to identify the root
cause.
I found an identical report from 2012 but it had no resolution:
https://github.com/typhoeus/typhoeus/issues/202
I also found related links:
* https://github.com/jruby/jruby/issues/231
* https://github.com/jruby/jruby/issues/752
=> spec/integration/rails: skip Typhoeus test on JRuby

.circleci/config.yml, .rubocop.yml, CHANGELOG.md, airbrake.gemspec, lib/airbrake/delayed_job.rb, lib/airbrake/sneakers.rb, spec/support/matchers/a_notice_with.rb
Airbrake Ruby no longer supports these versions as of
https://github.com/airbrake/airbrake-ruby/pull/663.
=> Dropped support for Ruby 2.3 & 2.4

README.md, lib/generators/airbrake_generator.rb, lib/generators/airbrake_initializer.rb.erb
This is bad engineering practice as it violates [the twelve-factor app
principles](https://12factor.net) (factor 3).
=> generators: do not embed creds into the config file

spec/apps/rack/rack_app.rb, spec/integration/rack/rack_spec.rb, spec/spec_helper.rb
DummyApp is defined by both Rack and Rails tests. Let's not shadow constants.
=> spec/apps: fix warning about redefined constants

README.md, airbrake.gemspec
These dependencies couldn't be bumped before because they dropped Ruby <2.5 support. Now that our requirement is Ruby 2.5+, we can bump them as well.
=> gemspec: bump stale dependencies

CHANGELOG.md
The linked in CHANGELOG updated in #1179 was wrong.
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
=> Fix up the PR number in PR 1179

.github/workflows/test.yml, .rubocop.yml, CHANGELOG.md, README.md, airbrake.gemspec, spec/integration/rails/rails_spec.rb
Some of our test dependencies start requiring Ruby 2.6+.
Ruby 2.5 was EOL on 31 Mar 2021, so it should be safe to move on.
=> Drop support for Ruby 2.5

CHANGELOG.md, lib/airbrake/rails/app.rb
Fixes https://github.com/airbrake/airbrake/issues/1177
(airbrake gem don't work with 7.0.0.alpha2 release)
Alternative to https://github.com/airbrake/airbrake/pull/1206
`glob?` on Rails 7+ raises error because Rails 7+ doesn't keep the route AST in
memory anymore. A Rails contributor who worked on the related code
[suggested][1] to use `Nodes::Star` instead, since that used to be the previous
implementation of the `glob?` method.
[1]: https://github.com/rails/rails/pull/43006#discussion_r783840849
=> rails/app: check for `Nodes::Star` instead of using `glob?`

.rubocop.yml, CHANGELOG.md, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/railtie.rb, spec/unit/rails/action_controller_notify_subscriber_spec.rb
Fixes bugged route stat reporting on Rails 7+ due to the fact that `@event.time`
returns milliseconds (but we want seconds). Therefore the time that we pass is
ahead by centuries, and our backend rejects such routes.
=> action_controller_notify_subscriber: use seconds as time on Rails 7+

lib/airbrake/rails/railtie.rb, lib/airbrake/rails/railties/action_controller_tie.rb, lib/airbrake/rails/railties/active_record_tie.rb, lib/airbrake/rails/railties/middleware_tie.rb
railties.rb has started violating Rubocop rules because it became too bloated. By factoring out the railtie code into separate classes we can organize it much better (and hopefully with less 🍝)
=> Refactor railties so that every railtie is a separate class

CHANGELOG.md, lib/airbrake/rails/railties/active_record_tie.rb
Fixes https://github.com/airbrake/airbrake/issues/1222
(Airbrake Gem Attempts to Connect to Database in Databaseless App in Rails 6)
Good article:
https://www.bigbinary.com/blog/rails-6-changed-activerecord-base-configurations-result-to-an-object
We also add a guard that makes sure there's an ActiveRecord configuration
present (it can be that ActiveRecord is required but not configured; why? I have
no idea but it did happen to our customer and he's got no clue either).
=> rails/railtie: read adapter info without requiring an active DB conn

CHANGELOG.md, lib/airbrake/rails/action_controller_notify_subscriber.rb, lib/airbrake/rails/event.rb, lib/airbrake/rails/railties/action_controller_tie.rb, spec/integration/rails/rails_spec.rb, spec/unit/rails/action_controller_notify_subscriber_spec.rb
Improves on 852ffd6219e3a6c3dba642c23fa8995279c06975.
While 852ffd6219e3a6c3dba642c23fa8995279c06975 was the correct fix, it was fixed
at the wrong place. Route stat reporting worked but other APM parts still
suffered from the same bug. I simply didn't notice that. I also wanted to make
the change testable.
The correct place to fix the bug is the Event class. The downside is that we
cannot write unit tests for it.
=> rails/event: convert milliseconds into seconds for #time

lib/airbrake/rails/railties/middleware_tie.rb
This just seems like a typo to me.  Both branches call `tie_rails_4_or_below_with_active_record`
```
$ be rails c
/Users/nickd/.rvm/gems/ruby-2.7.6@benchprep/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Traceback (most recent call last):
24: from bin/rails:4:in `<main>'
23: from bin/rails:4:in `require'
22: from /Users/nickd/.rvm/gems/ruby-2.7.6@benchprep/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
21: from /Users/nickd/.rvm/gems/ruby-2.7.6@benchprep/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
20: from /Users/nickd/.rvm/gems/ruby-2.7.6@benchprep/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:67:in `console' …
```
=> Fix middleware load order for Rails 4.x without ActiveRecord

lib/airbrake/sidekiq/retryable_jobs_filter.rb, spec/unit/sidekiq/retryable_jobs_filter_spec.rb
Previously, the @max_retries var was being used for both the global default retry limit as well as when a developer indicates they want error notifications before retries have been exhausted for a Sidekiq job. This results in an undesirable side effect for apps that:
* Do not pass max_retries as an arg to the RetryableJobsFilter initializer to indicate they want early notifications for errors when there are retries remaining
* Explicitly set a higher retry count than the global default for some jobs
Since Sidekiq may reuse worker threads, this will result in a situation where a thread may first execute a job with no retry limit explicitly set, which will load the global default into @max_retries. Later that same thread will be used to execute a job that has an explicit retry limit set, …
=> Separate var when overriding max retries before notify in Sidekiq jobs
