lib/airbrake/utils/params_cleaner.rb

* Don't modify data in place with collect!
* Don't try to "collect" over IO objects

This should fix #369

---

lib/rails/generators/airbrake/airbrake_generator.rb

Use proper capistrano hook depending on capistrano version

---

lib/airbrake/capistrano.rb
test/capistrano_test.rb

capistrano task should handle symbols for env
Fixes #393

capistrano task should handle symbols for env

---

resources/airbrake_2_4.xsd
test/notice_test.rb

This reverts commit df1c1e00c8157e549626acf0b0baa168382d9923.
Fixes #415 (Build failure on master)

Revert "start using remote XSD file when verifying XML in tests"

---

lib/airbrake/rails/controller_methods.rb
test/controller_methods_test.rb

When airbrake reports a controller error, it attempts to get information
about `current_user`. Airbrake assumes that getting `current_user` is a
safe operation. If there is an error while loading `current_user`
airbrake does not handle the error, and crashes. This both masks the
original error with a user loading error, and prevents either error
from being reported to airbrake.
This change rescues errors that occur when calling `current_user` or
`current_member`. If this happens, the user info sent to airbrake will be
empty.
We also handle any errors raised while attempting to fetch user defined
attributes on `current_user`. In this case the erroneous attribute is
not included in the user info, but any attributes that are successfully
fetched will still be included.

Protected against errors while gathering user details

---

lib/airbrake.rb
lib/airbrake/notice.rb
test/notice_test.rb

fixes https://github.com/airbrake/airbrake/issues/370

Add way to ignore all the exceptions

---

lib/airbrake/sidekiq.rb

This will allow airbrake helper to work with sidekiq 4

Relax sidekiq version dependency

---

README.md

Fixes #448 (Resque Readme Section)

README: fix Resque integration description

---

CHANGELOG.md
lib/airbrake/rack/user.rb
spec/unit/rack/user_spec.rb

rack/user: fix error when warden.user returns nil

---

CHANGELOG.md
lib/airbrake/capistrano/tasks.rb

This PR replaces https://github.com/airbrake/airbrake/pull/489. It adds the Rubocop special comments, which makes the test suite pass.

Specify RAILS_ENV and RACK_ENV in capistrano rake task

---

lib/airbrake.rb

Fix for issue https://github.com/airbrake/airbrake/issues/511

Change hash syntax for compatibility

---

Appraisals
gemfiles/rack.gemfile
gemfiles/rails_3.2.gemfile
gemfiles/rails_4.0.gemfile
gemfiles/rails_4.1.gemfile
gemfiles/rails_4.2.gemfile
gemfiles/rails_edge.gemfile
gemfiles/sinatra.gemfile

Appraisals: depend on unreleased version of delayed_job for rails_edge

---

docs/Migration_guide_from_v4_to_v5.md

I was changed since https://github.com/airbrake/airbrake/pull/530.

Migration guide: clarify the newest blacklisting/whitelisting API

---

docs/Migration_guide_from_v4_to_v5.md

* Adds ,'s to the guide required inside the hash
Fixes #560

Fix documentation

---

lib/airbrake/capistrano/tasks.rb

Use bundle exec rake in capistrano 3 task

---

Appraisals
circle.yml
gemfiles/rack.gemfile
gemfiles/rails_3.2.gemfile
gemfiles/rails_4.1.gemfile
gemfiles/rails_4.2.gemfile
gemfiles/rails_5.0.gemfile
gemfiles/rails_edge.gemfile
gemfiles/sinatra.gemfile

Rails 5 was released a few days ago.
`rails-edge` is `rails-5.1.0.alpha` for the time being.

Appraisals: add rails-5 appraisal

---

docs/Migration_guide_from_v4_to_v5.md

Alternative to #570
Thanks to: @equivalent

Migration Guide: mention ignore_only being removed from Airbrake v5

---

CHANGELOG.md
README.md
lib/airbrake/rack/middleware.rb
lib/airbrake/rack/notice_builder.rb
spec/apps/sinatra/composite_app/sinatra_app1.rb
spec/apps/sinatra/composite_app/sinatra_app2.rb
spec/integration/sinatra/sinatra_spec.rb
spec/unit/rack/middleware_spec.rb

rack: add support for multiple notifiers

---

README.md
lib/generators/airbrake_initializer.rb.erb

Based on https://github.com/airbrake/airbrake-ruby/pull/108.

README: explain how to integrate Rails' filter_parameters

---

README.md

Resolves #596 (Airbrake v4 deprecation)

README: remove mentions of v4

---

CHANGELOG.md
README.md
lib/airbrake.rb
lib/airbrake/rack/http_headers_filter.rb
lib/airbrake/rack/middleware.rb
lib/airbrake/rack/request_body_filter.rb
spec/unit/rack/http_headers_filter_spec.rb
spec/unit/rack/request_body_filter_spec.rb

Replaces: #650
Due to security concerns we now make this behaviour optional.

rack: factor out body collecting to a separate optional filter

---

circle.yml
gemfiles/rack.gemfile
gemfiles/rails_3.2.gemfile
gemfiles/rails_4.0.gemfile
gemfiles/rails_4.1.gemfile
gemfiles/rails_4.2.gemfile
gemfiles/rails_5.0.gemfile
gemfiles/rails_edge.gemfile
gemfiles/sinatra.gemfile

Also fix random failures along the way.

circle: fix build for JRuby

---

lib/airbrake/delayed_job/plugin.rb
lib/airbrake/resque/failure.rb
lib/airbrake/sidekiq/error_handler.rb
spec/unit/sidekiq/error_handler_spec.rb

With only one additional test for sidekiq, sorry.

Add additional check for not existing notice

---

CHANGELOG.md
lib/airbrake/version.rb

I would like to test the Logger integration better (enabled by default)
because it is a significant change.

Release v5.8.0.rc.1

---

lib/airbrake/rack/user.rb
spec/unit/rack/user_spec.rb

fixes: #try_current_user fails to get user when controller#current_user is a private method

fixes: #try_current_user when controller#current_user is private

---

Appraisals

`delayed_job_active_record` is not supporting it yet:
https://circleci.com/gh/airbrake/airbrake/1261

Appraisals: temporarily disable rails-edge

---

lib/airbrake.rb
lib/airbrake/rack.rb

Place all the dependencies required for Rack support in one file

---

README.md

Just came across this error.
Is that ok as a pull request ?

README.md : fix Airbrake.add_filter example

---

circle.yml

This build is expected to fail.

circle: restructure tests so they can fail properly

---

CHANGELOG.md
lib/airbrake/rake/tasks.rb
spec/unit/rake/tasks_spec.rb

Fixes #767 (Broken airbrake:deploy task)

rake/tasks: fix the deploy task

---

lib/airbrake/capistrano/capistrano2.rb

With these changes we don't need to ignore any Rubocop offences.

capistrano/capistrano2: simplify integration

---

CHANGELOG.md
lib/airbrake/rake/tasks.rb

Fixes https://github.com/airbrake/airbrake/issues/794

rake: fix error message for "airbrake:test"

---

.rubocop.yml
Appraisals
Gemfile
airbrake.gemspec
gemfiles/rails_5.1.gemfile
gemfiles/rails_edge.gemfile
spec/apps/rails/dummy_app.rb

* Repository https://github.com/gogovan/delayed_job was deleted
* Latest Rubocop doesn't support Ruby 2.0.0 anymore but we still do

 Fix build failure

---

README.md
airbrake.gemspec
lib/airbrake.rb
lib/airbrake/sneakers.rb
spec/unit/sneakers_spec.rb

Hi,
I want to add integration with the sneakers gem.
Sneakers uses bunny to connect to a rabbitmq server and provides workers.
Testsetup would be difficult, so I didn't made any tests.

Provide integration with sneakers gem

---

CHANGELOG.md
lib/airbrake/rails.rb

Fixes #821
(Rails API support)

rails: add support for Rails API/Metal

---

spec/integration/rails/rails_spec.rb

This fixes sporadic failures on JRuby:
https://circleci.com/gh/airbrake/airbrake/2115

spec/integration/rails: sleep for 2 seconds

---

spec/unit/sneakers_spec.rb

* use `subject` instead of the class name
* indentation fixes
* regexp fix

spec/unit/sneakers: cleanup

---

spec/integration/rails/rails_spec.rb

Airbrake Ruby v3.0.0.rc.9 uses this format (again).

integration/rails/rails: status_code -> statusCode

---

.rubocop.yml
spec/integration/rails/rails_spec.rb
spec/integration/shared_examples/rack_examples.rb
spec/unit/logger_spec.rb
spec/unit/rack/middleware_spec.rb
spec/unit/rake/tasks_spec.rb

rubocop: stop enforcing Layout/DotPosition

---

lib/airbrake/rails/active_job.rb
spec/integration/rack/rack_spec.rb
spec/integration/rails/rails_spec.rb
spec/integration/shared_examples/rack_examples.rb
spec/integration/sinatra/sinatra_spec.rb

This should fix our currently failing test suite. I tried to make tests as fast
as possible and as clean as possible, however I am still not happy with
them. They're slow and hard to follow. That said, this commit should unblock
releasing.

Refactor specs to use mocks

---

lib/airbrake.rb
lib/airbrake/action_cable.rb

I added code according to discussion in https://github.com/airbrake/airbrake/issues/885
I based it on 6.3.0 because that is a version I have currently in my main project.

WIP: Added support for exceptions in ActionCable

---

spec/spec_helper.rb
spec/unit/rake/tasks_spec.rb

* spec/unit/rake/tasks: hide all unwanted output
* spec_helper: delete banner

Clean up test suite

---

lib/airbrake/rails/action_controller_route_subscriber.rb
lib/airbrake/rails/app.rb
lib/airbrake/rails/event.rb
spec/unit/rails/action_controller_route_subscriber_spec.rb

We plan to add more business logic to it, so it's a good idea to start unit
testing this hook. I wrapped Rails APIs with our own, so we can mock the
wrappers and nicely unit test our own API.

rails: unit test route_subscriber

---

lib/airbrake/rails.rb

Initially, I wanted to make them separate, so that everything is
isolated. However, `airbrake.action_controller` loads things once
`action_controller` is ready. This is important for hooks. It's better to keep
things together, so if we need another integration, the chance of not loading
what we expect to load is lower.

rails: merge airbrake.action_controller & airbrake.http_breakdown

---

spec/unit/rack/instrumentable_spec.rb
spec/unit/rack/rack_spec.rb

This fixes sporadic test failures evidenced in:
https://circleci.com/gh/airbrake/airbrake/5560

spec/unit/rack: always clean up routes

---

CHANGELOG.md
README.md
lib/generators/airbrake_initializer.rb.erb

Background:
* The technology industry has began moving away from terms such as master/slave
and white list /blacklist.
* A recent tweet about this
https://twitter.com/leahculver/status/1269109776983547904

Rename "blacklist" to "blocklist"

---

.circleci/config.yml

circleci: use Ruby 2.7 instead of 2.7.0

---

.circleci/config.yml
CHANGELOG.md
airbrake.gemspec
spec/unit/sidekiq/retryable_jobs_filter_spec.rb
spec/unit/sidekiq_spec.rb

Drop support for Ruby 2.1

---

.circleci/config.yml
Appraisals
CHANGELOG.md
README.md
airbrake.gemspec
gemfiles/rails_4.1.gemfile
gemfiles/rails_4.2.gemfile
gemfiles/rails_5.0.gemfile
gemfiles/rails_5.1.gemfile
gemfiles/sinatra.gemfile
lib/airbrake/rails/curb.rb
lib/airbrake/rails/http_client.rb
lib/airbrake/rails/typhoeus.rb
spec/integration/rails/rails_spec.rb
spec/unit/sneakers_spec.rb

Drop support for Ruby 2.2

---

.github/workflows/test.yml
Appraisals
gemfiles/rails_5.2.gemfile
gemfiles/rails_6.1.gemfile
gemfiles/rails_7.0.gemfile
spec/apps/rails/dummy_app.rb
spec/integration/rails/rails_spec.rb

Also switch the delayed job library to https://github.com/Betterment/delayed,
which was blocking us from testing against Rails 7.0.
https://github.com/collectiveidea/delayed_job_active_record/issues/196 is still
unresolved.

Appraisals: test against Rails 7.0
